### ISSUE TITLE
Boundary values

### ISSUE THREAD

**Issue by IanaKhitsko** [Blackstee/Euro-diffusion#3]
https://github.com/Blackstee/Euro-diffusion/blob/f925cb1f621830945bd7c7152bbd164806ed63fb/structures/Country.py#L38

Can it be < 0 ? 

Same for other conditions. Can coordinates here be <0 and > 10 ?

**Comment by Blackstee** [comment]
The coordinates always have to be 0<= x <=10. It is checked on the stage of input processing.

The conditions you have mentioned are to avoid looking for unreal neighbors. For example, if the city has coordinates (5, 0) we don't have to check whether it has neighbors downside, for the city with coordinates (10, 5)  there is no sense to look for neighbors on the right side and so on.
