### ISSUE TITLE
Better to use "!" instead of "== False" 

### ISSUE THREAD

**Issue by LinaDovhaniuk** [Blackstee/Euro-diffusion#7]
https://github.com/Blackstee/Euro-diffusion/blob/f925cb1f621830945bd7c7152bbd164806ed63fb/structures/Country.py#L40

**Comment by Blackstee** [comment]
python does not have the "!" operator for condition checking. It can be used only in the format of "a!=b".

Instead of that, I will place "not", it is the Python analog.
